title: Heimdall Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://heimdall-controller.github.io

aux_links:
  GitHub Repository: https://github.com/heimdall-controller/heimdall-controller.github.io