title: Heimdall Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: www.heimdall.wiki

aux_links:
  GitHub Repository: https://github.com/heimdall-controller/heimdall-controller.github.io